import "./globals.css";
import type { Metadata } from "next";
import { Main } from "@/components/footer component/page";
import { Header } from "@/components/headerComponents/header";

export const metadata: Metadata = {
  title: "Axe",
  description: "Generated by create next app",
};

export default function Root({ children }: Readonly<{ children: React.ReactNode; }>)
 {
  return (
    <html lang="en" >
      <body className="dark:bg-black flex flex-col items-center" >
         <Header />
         {children}
         <Main/>
      </body>
    </html>
  );
}
